### ISSUE TITLE
blender script is failing to run

### ISSUE THREAD

**Issue by Sir-LoLz** [NoneGiven/MphRead#83] opened 2021-12-30 19:45 UTC
I have exported the room I want and have gotten the Blender Script for it. but it keeps giving an error on line 17.

`Error: Parsing errors in Document (see Blender Console)
Traceback (most recent call last):
  File "\import_MP9_CRYOCHASM.py", line 2134, in <module>
  File "\import_MP9_CRYOCHASM.py", line 17, in import_dae
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Parsing errors in Document (see Blender Console)`

I tried changing the dir to a straight link to the file and have removed the spaces ( MP9 CRYOCHASM_default to MP9_CRYOCHASM_default ) but that then gives this error 

`Traceback (most recent call last):
  File "\import_MP9_CRYOCHASM.py", line 2133, in <module>
  File "\import_MP9_CRYOCHASM.py", line 17, in import_dae
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy\ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
TypeError: Calling operator "bpy.ops.wm.collada_import" error, expected a string enum in ('INVOKE_DEFAULT', 'INVOKE_REGION_WIN', 'INVOKE_REGION_CHANNELS', 'INVOKE_REGION_PREVIEW', 'INVOKE_AREA', 'INVOKE_SCREEN', 'EXEC_DEFAULT', 'EXEC_REGION_WIN', 'EXEC_REGION_CHANNELS', 'EXEC_REGION_PREVIEW', 'EXEC_AREA', 'EXEC_SCREEN')
Error: Python script failed, check the message in the system console
`

to my knowledge, the mph_common.py plugin is installed. the data tab points to the common blender plugin path `C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\`

**Comment by NoneGiven** [comment] 2021-12-31 01:59
Can you share what lines 17-18 of the import script actually contain for you?

Also, you can try running the following in Blender's Scripting window:

```py
import bpy
bpy.ops.wm.collada_import(filepath = 'FULL_PATH_TO_YOUR.dae')
```

When I run this, it works fine with backslashes and spaces in the filename. If it doesn't work for you, please let me know the error and the full path string that you're trying.

You're right that `mph_common.py` is installed correctly, otherwise you wouldn't get past line 4.

**Comment by Sir-LoLz** [comment] 2021-12-31 03:10
ah sorry, I should have included that line. 

17 and 18 look like this `    bpy.ops.wm.collada_import(filepath =
        fr'MP9 CRYOCHASM\MP9 CRYOCHASM_{suffix}.dae')`

running the command you mentioned worked.

**Comment by NoneGiven** [comment] 2021-12-31 03:34
I see, the issue is that a relative path in `paths.txt` results in a relative path in the import script, which won't (always) work. I'll fix that in the next release, but in the meantime, you can replace the filename string in line 18 with the full file path before you run the import script.

There may also be an issue with the node animation, so I would change line 12 to `node_index = -1` as well. Room models don't have node animations, anyway.

**Comment by NoneGiven** [comment] 2022-01-04 17:00
The fixed version is out, and there's a workaround for the current version, so I'm closing this issue.

**Closed by NoneGiven** 2022-01-04 17:00 UTC
